name: Ubuntu 24.04 ARM arch support for RMVL

on:
  workflow_call:

jobs:
  package_pipe:
    name: Package on Ubuntu 24.04 (ARM arch)
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libeigen3-dev libopencv-dev pybind11-dev
        curl -sSL https://github.com/microsoft/onnxruntime/releases/download/v1.18.1/onnxruntime-linux-aarch64-1.18.1.tgz -o onnxruntime-linux-aarch64-1.18.1.tgz
        tar -xf onnxruntime-linux-aarch64-1.18.1.tgz
        sudo mkdir /usr/local/include/onnxruntime
        cd onnxruntime-linux-aarch64-1.18.1
        sudo cp -r include/* /usr/local/include/onnxruntime
        sudo cp -r lib /usr/local

    - name: Configure the project by CMake 
      # RMVL 1.x does not support Python, we also can use the CMake option -DBUILD_PYTHON=ON although it is not necessary
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_OPEN62541=ON

    - name: "Run build script: Unix Makefile"
      run: cmake --build ${{ github.workspace }}/build --parallel 4

    - name: Package RMVL
      run: |
        cd ${{ github.workspace }}/build
        cpack -G "DEB;TGZ" -D CPACK_PACKAGE_DIRECTORY=${{ github.workspace }}/build/out-package

    - name: Upload RMVL package
      uses: actions/upload-artifact@v4
      with:
        name: rmvl-u24arm-package
        path: |
          ${{ github.workspace }}/build/out-package/*.deb
          ${{ github.workspace }}/build/out-package/*.tar.gz
        retention-days: 1
        compression-level: 0
        if-no-files-found: error