name: Ubuntu 20.04 support for RMVL

on:
  workflow_call:

jobs:
  build_and_test:
    name: Build and test on Ubuntu 20.04
    runs-on: ubuntu-latest
    container:
      image: registry.cn-hangzhou.aliyuncs.com/cv-rmvl/rmvl-u20-base:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Configure the project by CMake
      # RMVL 1.x does not support Python, we also can use the CMake option -DBUILD_PYTHON=ON although it is not necessary
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_EXTRA=ON -DBUILD_TESTS=ON -DBUILD_PYTHON=ON

    - name: "Run build script: Unix Makefile"
      run: cmake --build ${{ github.workspace }}/build --parallel 4

    - name: "Run test script: ctest"
      run: cd ${{ github.workspace }}/build && ctest

    - name: Install the project by CMake
      run: cmake --install ${{ github.workspace }}/build

    - name: "Deploy: Checkout repository"
      uses: actions/checkout@v6
      with:
        repository: cv-rmvl/ci-workflow
        path: deploy-repo

    - name: "Deploy: Run deploy script"
      run: bash deploy-repo/deploy/scripts/build.sh
