name: Ubuntu 26.04 ARM arch support for RMVL

on:
  workflow_call:

jobs:
  build_and_test:
    name: Build and test on Ubuntu 26.04 (ARM arch)
    runs-on: ubuntu-26.04-arm
    steps:
    - name: "[RMVL] Checkout repository"
      uses: actions/checkout@v6

    - name: "[RMVL] Install dependencies"
      run: |
        echo "Installing dependencies by apt..."
        sudo apt update
        sudo apt install -y libeigen3-dev libopencv-dev python3-dev pybind11-dev socat
        echo -e "\033[1;34mInstalling dependencies by apt done.\033[0m"
        echo "Installing ONNX Runtime 1.27.0..."
        curl -sSL https://github.com/microsoft/onnxruntime/releases/download/v1.27.0/onnxruntime-linux-aarch64-1.27.0.tgz -o onnxruntime-linux-aarch64-1.27.0.tgz
        tar -xf onnxruntime-linux-aarch64-1.27.0.tgz
        sudo mkdir /usr/local/include/onnxruntime
        cd onnxruntime-linux-aarch64-1.27.0
        sudo cp -r include/* /usr/local/include/onnxruntime
        sudo cp -r lib /usr/local
        echo -e "\033[1;34mInstalling ONNX Runtime 1.27.0 done.\033[0m"

    - name: "[RMVL] Configure the project by CMake"
      # RMVL 1.x does not support Python, we also can use the CMake option -DBUILD_PYTHON=ON although it is not necessary
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_OPEN62541=ON -DBUILD_PYTHON=ON

    - name: "[RMVL] Run build script: Unix Makefile"
      run: cmake --build ${{ github.workspace }}/build --parallel

    - name: "[RMVL] Run test script: ctest"
      run: ctest --test-dir ${{ github.workspace }}/build

    - name: "[RMVL] Install the project by CMake"
      run: sudo cmake --install ${{ github.workspace }}/build

    - name: "[KDT] Checkout repository"
      uses: actions/checkout@v6
      with:
        repository: cv-rmvl/ci-workflow
        path: deploy-repo

    - name: "[KDT] Setup Python"
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: "[KDT] Install dependencies"
      run: python3 -m pip install -r deploy-repo/kdt/requirements.txt

    - name: "[KDT] Run testing script"
      run: python3 deploy-repo/kdt/test.py ci_guardian

    - name: "[KDT] Upload logs"
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: kdt-logs-u26-arm64
        path: deploy-repo/kdt/tmp/*.log
        if-no-files-found: ignore
        retention-days: 3
