name: Windows support for RMVL

on:
  workflow_call:

jobs:
  build_and_test:
    name: Build and test on Windows
    runs-on: windows-2022
    steps:
    - name: "[RMVL] Checkout repository"
      uses: actions/checkout@v6

    - name: "[RMVL] Configure the project by CMake"
      run: cmake -B ${{ github.workspace }}/build -DBUILD_OPEN62541=ON -DBUILD_TESTS=ON

    - name: "[RMVL] Run build script: Visual Studio"
      run: cmake --build ${{ github.workspace }}/build --parallel --config Release

    - name: "[RMVL] Run test script: ctest"
      run: ctest --test-dir ${{ github.workspace }}/build --build-config Release

    - name: "[RMVL] Install the project by CMake"
      run: cmake --install ${{ github.workspace }}/build --config Release

    - name: "[KDT] Checkout repository"
      uses: actions/checkout@v6
      with:
        repository: cv-rmvl/ci-workflow
        path: deploy-repo

    - name: "[KDT] Setup Python"
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: "[KDT] Install dependencies"
      run: python -m pip install -r deploy-repo\kdt\requirements.txt

    - name: "[KDT] Run testing script"
      run: python deploy-repo\kdt\test.py ci_guardian --rmvl-dir="${{ github.workspace }}\build\install"

    - name: "[KDT] Upload logs"
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: kdt-logs-windows
        path: deploy-repo/kdt/tmp/*.log
        if-no-files-found: ignore
        retention-days: 3
