name: Windows ARM arch support for RMVL

on:
  workflow_call:

jobs:
  build_and_test:
    name: Build and test on Windows (ARM arch)
    runs-on: windows-11-arm
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Configure the project by CMake 
      run: cmake -B ${{ github.workspace }}/build -DBUILD_OPEN62541=ON -DBUILD_TESTS=ON

    - name: "Run build script: Visual Studio"
      run: cmake --build ${{ github.workspace }}/build --parallel 4 --config Release

    - name: "Run test script: ctest"
      run: ctest --test-dir ${{ github.workspace }}/build --build-config Release

    - name: Install the project by CMake
      run: cmake --install ${{ github.workspace }}/build --config Release

    - name: "[Deploy] Checkout repository"
      uses: actions/checkout@v6
      with:
        repository: cv-rmvl/ci-workflow
        path: deploy-repo

    - name: "[Deploy] Run deploy script"
      run: .\deploy-repo\deploy\scripts\build.bat Release "${{ github.workspace }}\build\install"
